Fix compilation when NEED_G_SLIST_FREE_FULL is defined
To use the replacement for g_slist_free_full() both compat.h and
glib-helper.h need to be included.

Fixes:
gobex/gobex.c:911: error: implicit declaration of function 'g_slist_free_full'
tools/test-server.c:344: error: implicit declaration of function ‘g_slist_free_full’